---
title: "owner-analysis"
format: html
---


author: Mayra

##Exercise: Explore, Clean, and Wrangle Data

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
```

```{r}
lobster_abundance <- read_csv("data/Lobster_Abundance_All_Years_20220829.csv")
```

12.2 Question 1

```{r}
lobster_abundance <- lobster_abundance %>% 
    mutate(SIZE_MM = na_if(SIZE_MM, -99999))
head(lobster_abundance)
```


12.3 Question 2

```{r}
not_napl <- lobster_abundance %>% 
    filter(SITE != "NAPL")
head(lobster_abundance)
```

12.3 Question 3

```{r}
aque_70mm <- lobster_abundance %>% 
    filter(SITE == "AQUE" & SIZE_MM >= 70)
head(lobster_abundance)
```


## Exercise: Data Visualization


Question 7

```{r}
ggplot(data = lobster_abundance, aes(x = SIZE_MM)) +
    geom_histogram() +
    facet_wrap(~SITE)
head(lobster_abundance)
```


Question 8

```{r}
lobsters_summarize <- lobster_abundance %>% 
  group_by(SITE, YEAR) %>% 
  summarize(COUNT = n())
head(lobsters_summarize)
```

Question 8 part 2

```{r}
# line plot
ggplot(data = lobsters_summarize, aes(x = YEAR, y = COUNT)) +
  geom_line(aes(color = SITE)) 
head(lobsters_summarize)

# line and point plot
ggplot(data = lobsters_summarize, aes(x = YEAR, y = COUNT)) +
  geom_point(aes(color = SITE)) +
  geom_line(aes(color = SITE)) 
head(lobsters_summarize)
```

Question 9

```{r}
# line plot
ggplot(data = lobsters_summarize, aes(x = YEAR, y = COUNT)) +
  geom_line(aes(color = SITE))+
  geom_line(aes(color = SITE))
head(lobsters_summarize)

ggsave("fig/lobsters_summarize_yearcount.jpg")

```

