---
title: "Collaborator Analysis"
author: "Julia Lober"     
format: html
---

## Exercise: Explore, Clean, and Wrangle Data

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(janitor)
```

```{r}
lobster_traps <- read_csv("../data/Lobster_Trap_Counts_All_Years_20210519.csv")
```

```{r}
colnames(lobster_traps)
glimpse(lobster_traps)
```

```{r}
lobster_traps_clean <- lobster_traps %>% 
  clean_names() %>% 
  mutate(traps = na_if(traps, -99999))
unique(lobster_traps_clean$traps)
colnames(lobster_traps_clean)
```

## Filter practice 

Filter out anything from the NAPL site (Naples Reef)

```{r}
lobster_no_napl <- lobster_traps_clean %>% 
  filter(site != "NAPL")
unique(lobster_no_napl$site)
```

```{r}
lobster_carp <- lobster_traps_clean %>% 
  filter(site == "CARP" & traps > 20)
head(lobster_carp)
```

## Data Visualization

```{r}
lobster_traps_clean %>% 
  ggplot() +
    geom_histogram(aes(x = traps)) + 
    facet_wrap(~ year)

```

```{r}
lobster_traps_clean %>% 
  summarize(total_traps = sum(traps, na.rm = TRUE),
            .by = c(site, year)) %>% 
  ggplot() +
    geom_line(aes(x = year, y = total_traps, color = site)) +
    geom_point(aes(x = year, y = total_traps, color = site)) 
```
```{r}
lobster_traps_clean %>% 
  filter(year %in% c(2019:2021)) %>% 
  mutate(fishing_pressure = if_else(traps >= 8,
                                    "high",
                                    "low")) %>% 
  summarize(count = n(),
            .by = c(site, fishing_pressure)) %>% 
  drop_na() %>% 
  ggplot() + 
    geom_col(aes(x = site, y = count, fill = fishing_pressure))

```

